name: UiPath Orchestrator Pipeline

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  pack:
    runs-on: windows-latest
    outputs:
      pack_status: ${{ steps.pack-step.outcome }}
    steps:
      - uses: actions/checkout@v4

      - name: Download NuGet
        shell: pwsh
        run: |
          curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      - name: Install UiPath CLI (query feed for latest version)
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $feed = "https://pkgs.dev.azure.com/uipath/Public.Feeds/_packaging/UiPath-Official/nuget/v3/index.json"
          $candidates = @("UiPath.CLI.Windows","UiPath.CLI","UiPath.Cli.Windows","UiPath.Cli")
          $pkg = $null; $ver = $null
          foreach ($n in $candidates) {
            try {
              Write-Host "Querying versions for $n from feed..."
              $lines = & .\nuget.exe list $n -Source $feed -AllVersions -Prerelease 2>$null
              if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($lines)) { continue }
              $versions = @()
              foreach ($ln in $lines) {
                if ($ln -match "^$n\s+([0-9][0-9A-Za-z\.-]*)") { $versions += $Matches[1] }
              }
              if ($versions.Count -gt 0) {
                $sorted = $versions | Sort-Object {[version]($_ -replace "-.*$","0")} , $_ | Select-Object -Unique
                $ver = $sorted[-1]
                $pkg = $n
                break
              }
            } catch { Write-Host ("list fail for {0}: {1}" -f $n, $_.Exception.Message) }
          }
          if (-not $pkg -or -not $ver) { Write-Host "Could not resolve UiPath CLI package/version from feed."; exit 1 }
          Write-Host "Installing $pkg version $ver from feed..."
          & .\nuget.exe install $pkg -Version $ver -Source $feed -OutputDirectory .\uipath-cli -NonInteractive -NoCache -DirectDownload
          if ($LASTEXITCODE -ne 0) { Write-Host "nuget install failed"; exit 1 }

      - name: Run pack and capture log
        id: pack-step
        shell: pwsh
        run: |
          $cli = Get-ChildItem .\uipath-cli -Recurse -Filter uipcli.exe | Select-Object -First 1
          if (-not $cli) { Write-Host "uipcli.exe not found"; Get-ChildItem .\uipath-cli -Recurse; exit 1 }
          & $cli.FullName pack --input "Golden_Template" --output ".\dist" --version "1.0.${{ github.run_number }}" --type Process 2>&1 | Tee-Object pack.log
        continue-on-error: false

      - name: Upload pack artifacts and log
        uses: actions/upload-artifact@v4
        with:
          name: uipath-pack-results
          path: |
            .\dist\*.nupkg
            pack.log

  analyze:
    needs: pack
    runs-on: ubuntu-latest
    outputs:
      has_errors: ${{ steps.scan.outputs.has_errors }}
    steps:
      - name: Download pack artifacts
        uses: actions/download-artifact@v4
        with:
          name: uipath-pack-results
          path: ./uipath-pack-results

      - name: Inspect pack.log
        id: scan
        run: |
          if [ -f ./uipath-pack-results/pack.log ]; then
            echo "---- tail pack.log ----"
            tail -n 200 ./uipath-pack-results/pack.log || true
            if grep -i -E "exception|error|failed|Unable to find package" ./uipath-pack-results/pack.log >/dev/null; then
              echo "Pack produced errors."
              echo "has_errors=true" >> "$GITHUB_OUTPUT"
            else
              echo "No obvious errors found in pack.log."
              echo "has_errors=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "pack.log not found in artifacts"
            echo "has_errors=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Post PR comment with summary
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const runUrl = `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const conclusion = (await github.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: parseInt(process.env.GITHUB_RUN_ID)
            })).data.conclusion || 'unknown';
            const body = `UiPath orchestration run [#${process.env.GITHUB_RUN_ID}](${runUrl}) concluded: **${conclusion}**.\n\nArtifacts: uipath-pack-results (pack.log + .nupkg if produced).`;
            await github.issues.createComment({
              ...context.repo,
              issue_number: context.payload.pull_request.number,
              body
            });

  autofix:
    needs: analyze
    if: ${{ needs.analyze.outputs.has_errors == 'true' && github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Attempt simple fixes
        run: |
          set -euo pipefail
          sudo apt-get update -y >/dev/null 2>&1 || true
          sudo apt-get install -y jq >/dev/null 2>&1 || true
          FILE="Golden_Template/project.json"
          if [ -f "$FILE" ]; then
            TMP=$(mktemp)
            jq '.dependencies |= (."UiPath.System.Activities"="[24.10.0,25.0.0)", ."UiPath.UIAutomation.Activities"="[24.10.0,25.0.0)", ."UiPath.Excel.Activities"="[2.24.0,3.0.0)", ."UiPath.Testing.Activities"="[24.10.0,25.0.0)")' "$FILE" > "$TMP" && mv "$TMP" "$FILE"
            echo "Adjusted dependency ranges in project.json"
          else
            echo "project.json not found; skipping dependency adjustments"
          fi
      - name: Commit and push fixes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "ci: widen UiPath Activities dependency ranges to fix pack"
            git push
          else
            echo "No changes to push."
          fi